{
 "title": "Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodename",
    "query": "SHOW TAG VALUES FROM \"uptime\" WITH KEY = \"nodename\""
   }
  ]
 },
 "panels": [
  {
   "title": "Load avg 1/5/15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load avg 1m",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Load avg 5m",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Load avg 15m",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total CPU cores",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LA 1m/Medium",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"value\") FROM \"medium\".\"load1/medium\" WHERE time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "LA 1m/Long",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"value\") FROM \"long\".\"load1/long\" WHERE time < now() - 672h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall Cluster CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT sum(\"value\") FROM \"cpu/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Request",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT sum(\"value\") FROM \"cpu/request\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"cpu/usage_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"cpu/usage_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT sum(\"value\") FROM \"cpu/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Request $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT sum(\"value\") FROM \"cpu/request\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"cpu/usage_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(1m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"cpu/usage_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Individual CPU Usage: $nodename",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT sum(\"value\") FROM \"cpu/limit\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Request $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT sum(\"value\") FROM \"cpu/request\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"cpu/usage_rate/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() -24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Cluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value\") FROM \"memory/usage\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/working_set",
     "query": "SELECT sum(\"value\") FROM \"memory/working_set\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "query": "SELECT sum(\"value\") FROM \"memory/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Request",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/request",
     "query": "SELECT sum(\"value\") FROM \"memory/request\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/usage/medium\" WHERE (\"type\" = 'node') AND time < now() -24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set/Medium",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/working_set/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/usage/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set/Long",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/working_set/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value\") FROM \"memory/usage\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/working_set",
     "query": "SELECT sum(\"value\") FROM \"memory/working_set\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "query": "SELECT sum(\"value\") FROM \"memory/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Request $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/request",
     "query": "SELECT sum(\"value\") FROM \"memory/request\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/usage/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/working_set/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/usage/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Working Set/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/working_set/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Individual Node Memory Usage: $nodename",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value\") FROM \"memory/usage\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/working_set",
     "query": "SELECT sum(\"value\") FROM \"memory/working_set\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "query": "SELECT sum(\"value\") FROM \"memory/limit\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Request $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/request",
     "query": "SELECT sum(\"value\") FROM \"memory/request\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/usage/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Working Set/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/working_set/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/usage/long\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Working Set/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/working_set/long\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Cluster Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Tx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/rx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Tx/Medium",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/tx_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx/Medium",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/rx_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Tx/Long",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/tx_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx/Long",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/rx_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Tx $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/rx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Tx/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/tx_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/rx_rate/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Tx/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/tx_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Rx/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/rx_rate/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Individual Node Network Usage: $nodename",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Tx $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Rx $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/rx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Tx/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/tx_rate/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Rx/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/rx_rate/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Tx/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/tx_rate/long\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Rx/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/rx_rate/long\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    }
   ]
  },
  {
   "title": "Overall Cluster Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"filesystem/usage\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/limit",
     "query": "SELECT sum(\"value\") FROM \"filesystem/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"medium\".\"filesystem/usage/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"long\".\"filesystem/usage/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Usage by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"filesystem/usage\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/limit",
     "query": "SELECT sum(\"value\") FROM \"filesystem/limit\" WHERE \"type\" = node AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"medium\".\"filesystem/usage/medium\" WHERE (\"type\" = 'node') AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    },
    {
     "alias": "Usage/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"long\".\"filesystem/usage/long\" WHERE (\"type\" = 'node') AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" }
     ]
    }
   ]
  },
  {
   "title": "Individual Filesystem Usage: $nodename",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"filesystem/usage\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Limit $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/limit",
     "query": "SELECT sum(\"value\") FROM \"filesystem/limit\" WHERE \"type\" = node AND \"nodename\" =~ /$nodename$/ AND $timeFilter GROUP BY time($interval), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage/Medium $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"medium\".\"filesystem/usage/medium\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    },
    {
     "alias": "Usage/Long $tag_nodename",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "nodename" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "filesystem/usage",
     "query": "SELECT sum(\"value\") FROM \"long\".\"filesystem/usage/long\" WHERE (\"type\" = 'node' AND \"nodename\" =~ /$nodename$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"nodename\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "node" },
      { "condition": "AND", "key": "nodename", "operator": "=~", "value": "/$nodename$/" }
     ]
    }
   ]
  }
 ]
}