{
 "title": "Pods",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "SHOW TAG VALUES FROM \"uptime\" WITH KEY = \"namespace_name\""
   },
   {
    "name": "podname",
    "query": "SHOW TAG VALUES FROM \"uptime\" WITH KEY = \"pod_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Individual CPU Usage: $namespace $podname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "Usage $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Limit $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/limit",
     "query": "SELECT sum(\"value\") FROM \"cpu/limit\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Request $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/request",
     "query": "SELECT sum(\"value\") FROM \"cpu/request\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Usage/Medium $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"cpu/usage_rate/medium\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Usage/Long $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu/usage_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"cpu/usage_rate/long\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Individual Memory Usage: $namespace $podname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Usage $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value\") FROM \"memory/usage\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Limit $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/limit",
     "query": "SELECT sum(\"value\") FROM \"memory/limit\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Request $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/request",
     "query": "SELECT sum(\"value\") FROM \"memory/request\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Working Set $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/working_set",
     "query": "SELECT sum(\"value\") FROM \"memory/working_set\" WHERE \"type\" = pod_container AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Usage/Medium $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/usage/medium\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Working Set/Medium $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"memory/working_set/medium\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Usage/Long $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/usage/long\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Working Set/Long $namespace $podname $tag_container_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory/usage",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"memory/working_set/long\" WHERE (\"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h), \"container_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Individual Network Usage: $namespace $podname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Tx $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/tx_rate\" WHERE \"type\" = pod AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Rx $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/rx_rate",
     "query": "SELECT sum(\"value\") FROM \"network/rx_rate\" WHERE \"type\" = pod AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Tx/Medium $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/tx_rate/medium\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Rx/Medium $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"medium\".\"network/rx_rate/medium\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 24h AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Tx/Long $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/tx_rate/long\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "Rx/Long $namespace $podname",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network/tx_rate",
     "query": "SELECT sum(\"value_mean\") FROM \"long\".\"network/rx_rate/long\" WHERE (\"type\" = 'pod' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/) AND time < now() - 672h AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  }
 ]
}