apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: monitoring-app
  resourceVersion: "0.0.0"
  namespace: monitoring
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-install
      spec:
        template:
          metadata:
            name: monitoring-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:buster
                command: ["/bin/sh", "/var/lib/gravity/resources/install.sh"]
  update:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-update
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: monitoring-app-update
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: monitoring-hook:0.0.1
                command: ["/usr/bin/dumb-init", "/update.sh"]
  rollback:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-rollback
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: monitoring-app-rollback
          spec:
            restartPolicy: Never
            containers:
              - name: hook
                image: monitoring-hook:0.0.1
                command: ["/usr/bin/dumb-init", "/rollback.sh"]
  uninstall:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: monitoring-app-uninstall
      spec:
        template:
          metadata:
            name: monitoring-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: hook
                image: quay.io/gravitational/debian-tall:stretch
                command: ["/bin/sh", "/var/lib/gravity/resources/uninstall.sh"]
