apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cfg
  namespace: kube-system
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/web/grafana
    [paths]
    provisioning = /etc/grafana/provisioning
    data = /var/lib/grafana
    logs = /var/log/grafana
    [auth.anonymous]
    # enable anonymous access
    enabled = true
