apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: kube-system
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s/web/grafana
    [data]
    provisioning = /etc/grafana/provisioning
    data = /var/lib/grafana
    logs = /var/log/grafana
