---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: monitoring
    component: heapster
  name: heapster
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: heapster
  template:
    metadata:
      labels:
        app: monitoring
        component: heapster
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        gravitational.io/k8s-role: master
      securityContext:
        runAsUser: -1
      containers:
      - name: heapster
        image: monitoring-heapster:latest
        command:
        - /usr/bin/dumb-init
        - /heapster
        - --source=kubernetes:https://kubernetes.default.svc.cluster.local?kubeletPort=10250&kubeletHttps=true&inClusterConfig=false&auth=/etc/kubernetes/kubectl.kubeconfig
        - --sink=influxdb:http://influxdb.monitoring.svc:8086
        volumeMounts:
        - name: certificates
          mountPath: /var/lib/gravity/secrets
        - name: configs
          mountPath: /etc/kubernetes
      volumes:
      - name: certificates
        hostPath:
          path: /var/lib/gravity/secrets
      - name: configs
        hostPath:
          path: /etc/kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
  name: heapster
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: monitoring
    component: heapster
