---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: monitoring-high-priority
value: 1000000
globalDefault: false
description: "This priority class for monitoring application pods."
