---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-influxdb-creds
  namespace: monitoring
type: Opaque
data:
  username: dGVsZWdyYWY=
  password: bllMNU1sdEREeHFSTlFxMEVsZkY=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-influxdb-creds
  namespace: monitoring
data:
  username: Z3JhZmFuYQ==
  password: cGRGY29ma2NHYllIekRZMUdadmg=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQtZ29lcy1oZXJlCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb
  namespace: monitoring
type: Opaque
data:
  username: cm9vdA==
  password: b1lIV3gyVDlmQVd3SzdsZTRrZDY=
