---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: monitoring
    component: telegraf
  name: telegraf
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: telegraf
  template:
    metadata:
      labels:
        app: monitoring
        component: telegraf
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      containers:
      - name: telegraf
        image: monitoring-telegraf:latest
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf-node
  namespace: kube-system
  labels:
    app: monitoring
    component: telegraf
spec:
  selector:
    matchLabels:
      app: monitoring
      component: telegraf
  template:
    metadata:
      labels:
        app: monitoring
        component: telegraf
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring
      tolerations:
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      containers:
        - name: telegraf
          image: monitoring-telegraf:latest
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/run-node.sh"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          volumeMounts:
            - name: certificates
              mountPath: /var/lib/gravity/secrets
      volumes:
        - name: certificates
          hostPath:
            path: /var/lib/gravity/secrets
