---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: monitoring
    component: telegraf
  name: telegraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: telegraf
  template:
    metadata:
      labels:
        app: monitoring
        component: telegraf
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      containers:
      - name: telegraf
        image: monitoring-telegraf:latest
        env:
          - name: INFLUXDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: username
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: password
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf-node-master
  namespace: monitoring
  labels:
    app: monitoring
    component: telegraf
    node: master
spec:
  selector:
    matchLabels:
      app: monitoring
      component: telegraf
      node: master
  template:
    metadata:
      labels:
        app: monitoring
        component: telegraf
        node: master
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      nodeSelector:
        gravitational.io/k8s-role: master
      serviceAccountName: monitoring
      tolerations:
        # allows to run on master nodes
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      containers:
        - name: telegraf
          image: monitoring-telegraf:latest
          command: ["/usr/bin/dumb-init", "--"]
          args:
            - /usr/bin/telegraf
            - --config
            - /etc/telegraf/telegraf-node-master.conf
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: password
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          volumeMounts:
            - name: certificates
              mountPath: /var/lib/gravity/secrets
      volumes:
        - name: certificates
          hostPath:
            path: /var/lib/gravity/secrets
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: telegraf-node-worker
  namespace: monitoring
  labels:
    app: monitoring
    component: telegraf
    node: worker
spec:
  selector:
    matchLabels:
      app: monitoring
      component: telegraf
      node: worker
  template:
    metadata:
      labels:
        app: monitoring
        component: telegraf
        node: worker
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      nodeSelector:
        gravitational.io/k8s-role: node
      serviceAccountName: monitoring
      securityContext:
        runAsUser: -1
      containers:
        - name: telegraf
          image: monitoring-telegraf:latest
          command: ["/usr/bin/dumb-init", "--"]
          args:
            - /usr/bin/telegraf
            - --config
            - /etc/telegraf/telegraf-node.conf
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telegraf-influxdb-creds
                  key: password
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
          volumeMounts:
            - name: certificates
              mountPath: /var/lib/gravity/secrets
      volumes:
        - name: certificates
          hostPath:
            path: /var/lib/gravity/secrets
