apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring
    component: watcher
  name: watcher
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
      component: watcher
  template:
    metadata:
      labels:
        app: monitoring
        component: watcher
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      serviceAccountName: monitoring
      tolerations:
      - key: "gravitational.io/runlevel"
        value: system
        operator: Equal
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: watcher
          image: watcher:latest
          securityContext:
            runAsUser: -1
          args:
            - --mode=alerts
