apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: leader.telekube.local:5000/prometheus/alertmanager
  nodeSelector:
    gravitational.io/k8s-role: master
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  containers:
    - name: mta
      image: leader.telekube.local:5000/monitoring-mta:1.0.0
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: alertmanager
              alertmanager: main
  tolerations:
  - key: "gravitational.io/runlevel"
    value: system
    operator: Equal
  # allows to run on master nodes
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  version: v0.16.2
