apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: leader.telekube.local:5000/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
    gravitational.io/k8s-role: master
  # will be auto-scaled by the watcher in a multi-node cluster
  replicas: 1
  priorityClassName: monitoring-high-priority
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  containers:
    - name: mta
      image: leader.telekube.local:5000/monitoring-mta:1.0.0
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: alertmanager
              alertmanager: main
  storage:
    hostPath:
      path: /var/lib/gravity/monitoring
  tolerations:
  # tolerate any taint
  - operator: "Exists"
  version: v0.18.0
  
