apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: gravity-k8s-rules
  namespace: monitoring
spec:
  groups:
  - name: cluster.rules
    rules:
      # Total number of CPU cores in the cluster.
      - expr: |
          sum(instance:node_num_cpu:sum)
        record: cluster:cpu_total
      # Cluster-wide CPU usage rate in percent.
      - expr: |
          (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))) * 100
        record: cluster:cpu_usage_rate
      # Cluster-wide total RAM in bytes.
      - expr: |
          sum(node_memory_MemTotal_bytes{job="node-exporter"})
        record: cluster:memory_total_bytes
      # Cluster-wide RAM usage in bytes.
      - expr: |
          sum(node_memory_MemTotal_bytes{job="node-exporter"}) - sum(node_memory_MemAvailable_bytes{job="node-exporter"})
        record: cluster:memory_usage_bytes
      # Cluster-wide RAM usage rate in percent.
      - expr: |
          (1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(kube_node_status_allocatable_memory_bytes)) * 100
        record: cluster:memory_usage_rate
  - name: sysctl
    rules:
    - alert: BrNetfilterMissing
      annotations:
        message: Bridge netfilter is disabled on node {{ $labels.node }}
      expr: max_over_time(satellite_sysctl_br_netfilter[1h]) unless satellite_sysctl_br_netfilter or satellite_sysctl_br_netfilter == 0
      for: 5m
      labels:
        severity: critical
    - alert: IPv4ForwardingMissing
      annotations:
        message: IPv4 forwarding is disabled on node {{ $labels.node }}
      expr: max_over_time(satellite_sysctl_ipv4_forwarding[1h]) unless satellite_sysctl_ipv4_forwarding or satellite_sysctl_ipv4_forwarding == 0
      for: 5m
      labels:
        severity: critical
  - name: docker
    rules:
    - alert: DockerDown
      annotations:
        message: Docker daemon is down on host {{ $labels.node }}
      expr: satellite_docker_health == 0
      for: 5m
      labels:
        severity: critical
  - name: node-resources
    rules:
    - alert: NodeCPUHighUsage
      annotations:
        message: Node {{ $labels.node }} has high cpu usage.
      expr: |
        instance:node_cpu_utilization:rate1m * 100 > 75 and instance:node_cpu_utilization:rate1m * 100 <= 90
      for: 30m
      labels:
        severity: warning
    - alert: NodeCPUHighUsage
      annotations:
        message: Node {{ $labels.node }} has high cpu usage.
      expr: |
        instance:node_cpu_utilization:rate1m * 100 > 90
      for: 5m
      labels:
        severity: critical
    - alert: NodeMemoryHighUsage
      annotations:
        message: Node {{ $labels.node }} has high memory usage.
      expr: |
        instance:node_memory_utilization:ratio * 100 > 80 and instance:node_memory_utilization:ratio * 100 <= 90
      for: 30m
      labels:
        severity: warning
    - alert: NodeMemoryHighUsage
      annotations:
        message: Node {{ $labels.node }} has high memory usage.
      expr: |
        instance:node_memory_utilization:ratio * 100 > 90
      for: 5m
      labels:
        severity: critical
