kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nethealth.fullname" . }}
  labels:
    {{- include "nethealth.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nethealth.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nethealth.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
