{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nethealth.fullname" . }}
  labels:
    {{- include "nethealth.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
{{- end }}
