{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nethealth.serviceAccountName" . }}
  labels:
    {{- include "nethealth.labels" . | nindent 4 }}
{{- end }}
