{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "watcher.fullname" . }}:autoscaler"
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
{{- end }}
