{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ template "watcher.fullname" . }}:autoscaler"
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - privileged
  - apiGroups:
      - monitoring.coreos.com
    verbs:
      - get
      - list
      - watch
      - update
    resources:
      - prometheuses
      - alertmanagers
{{- end }}
