{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ template "watcher.fullname" . }}:autoscaler"
  labels:
    {{- include "watcher.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "watcher.serviceAccountName" . }}-autoscaler"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ template "watcher.fullname" . }}:autoscaler"
{{- end }}
